import type { Metadata } from "next";
import { Jost, Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "EngwiAI",
  description: "Generated by create next app",
  applicationName: "EngwiAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${montserrat.variable} antialiased`}>
        <div className="fixed inset-0 -z-10 backdrop-blur-[6px]"></div>
        <main className="container mx-auto px-3 sm:px-4 lg:px-5 max-w-7xl">
          {children}
        </main>
      </body>
    </html>
  );
}
