# =====EXAMPLE======
# Nginx needed!!

# services:
#   postgres:
#     image: postgres:17
#     container_name: postgres
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "${PORT}:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#   backend:
#     build:
#       context: ./backend
#       target: production
#     container_name: backend
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
#     env_file:
#       - ./backend/.env.local
#     restart: unless-stopped
#   frontend:
#     build:
#       context: ./frontend
#       target: production
#     container_name: frontend
#     depends_on:
#       - backend
#     environment:
#       NEXT_PUBLIC_API_URL: "http://backend:4200/api/"
#     env_file:
#       - ./frontend/.env.local
#     restart: unless-stopped

# volumes:
#   postgres_data:
